#!/usr/bin/env python3                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                        
import re                                                                                                                                                                                                                                                  
import pyperclip                                                                                                                                                                                                                                           
from rich.console import Console                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                        
console = Console(highlight=False)                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                        
# Global storage for code blocks                                                                                                                                                                                                                           
code_blocks = {}                                                                                                                                                                                                                                           
code_block_counter = 0                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                        
def reset_code_blocks():                                                                                                                                                                                                                                   
    """Reset the code block counter and storage."""                                                                                                                                                                                                        
    global code_block_counter, code_blocks                                                                                                                                                                                                                 
    code_block_counter = 0                                                                                                                                                                                                                                 
    code_blocks = {}                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                        
def process_markdown_for_code_blocks(content):                                                                                                                                                                                                             
    """                                                                                                                                                                                                                                                    
    Process markdown content to identify and number code blocks.                                                                                                                                                                                           
    Returns the modified content with numbered code blocks.                                                                                                                                                                                                
    """                                                                                                                                                                                                                                                    
    global code_block_counter, code_blocks                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                        
    # Reset counter for each new message                                                                                                                                                                                                                   
    reset_code_blocks()                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                        
    # Pattern to match code blocks: ```[language]\ncode```                                                                                                                                                                                                 
    pattern = r"```(\w*)\n(.*?)```"                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                        
    def replace_code_block(match):                                                                                                                                                                                                                         
        global code_block_counter                                                                                                                                                                                                                          
        language = match.group(1)                                                                                                                                                                                                                          
        code = match.group(2)                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                        
        # Increment counter and store code                                                                                                                                                                                                                 
        code_block_counter += 1                                                                                                                                                                                                                            
        code_blocks[code_block_counter] = code                                                                                                                                                                                                             
                                                                                                                                                                                                                                                        
        # Format with language and copy reference                                                                                                                                                                                                          
        lang_indicator = language if language else ""                                                                                                                                                                                                      
        return f"```{lang_indicator}\n{code}``` [Copy #{code_block_counter}]"                                                                                                                                                                              
                                                                                                                                                                                                                                                        
    # Replace all code blocks in the content                                                                                                                                                                                                               
    modified_content = re.sub(pattern, replace_code_block, content, flags=re.DOTALL)                                                                                                                                                                       
                                                                                                                                                                                                                                                        
    return modified_content                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                        
def handle_copy_command(command):                                                                                                                                                                                                                          
    """                                                                                                                                                                                                                                                    
    Handle copy commands like 'copy 1' or 'copy #1'.                                                                                                                                                                                                       
    Returns True if command was handled, False otherwise.                                                                                                                                                                                                  
    """                                                                                                                                                                                                                                                    
    # Match patterns like "copy 1", "copy #1", "copy1"                                                                                                                                                                                                     
    match = re.match(r'^copy\s*#?(\d+)$', command.strip().lower())                                                                                                                                                                                         
    if match:                                                                                                                                                                                                                                              
        try:                                                                                                                                                                                                                                               
            block_num = int(match.group(1))                                                                                                                                                                                                                
            if block_num in code_blocks:                                                                                                                                                                                                                   
                pyperclip.copy(code_blocks[block_num])                                                                                                                                                                                                     
                console.print(f"[green]✓ Copied code block #{block_num} to clipboard![/]")                                                                                                                                                                 
                return True                                                                                                                                                                                                                                
            else:                                                                                                                                                                                                                                          
                console.print(f"[yellow]No code block #{block_num} found in this conversation.[/]")                                                                                                                                                        
                return True                                                                                                                                                                                                                                
        except (ValueError, IndexError):                                                                                                                                                                                                                   
            console.print("[red]Invalid copy command. Use 'copy #' where # is the code block number.[/]")                                                                                                                                                  
            return True                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                        
    return False                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                        
def get_copy_help_text():                                                                                                                                                                                                                                  
    """Returns help text for copying code blocks."""                                                                                                                                                                                                       
    if code_block_counter > 0:                                                                                                                                                                                                                             
        return "\n[dim]To copy a code block, type 'copy #' where # is the number (e.g., 'copy 1').[/]"                                                                                                                                                     
    return "" 